// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { publicSupabaseKey, publicSupabaseUrl } from '@/lib/runtime-env';

const SUPABASE_URL = publicSupabaseUrl || "https://placeholder.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = publicSupabaseKey || "placeholder-public-anon-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
